apiVersion: 1

datasources:
  - name: Fraud-MySQL
    uid: fraud-mysql
    type: mysql
    access: proxy
    url: mysql:3306
    user: fraud_user
    secureJsonData:
      password: fraud_pass
    jsonData:
      database: fraud_db
      maxOpenConns: 25
      maxIdleConns: 25
      connMaxLifetime: 14400
      timeInterval: 5s
      tlsAuth: false
      tlsAuthWithCACert: false
    editable: true
    isDefault: true
